### ISSUE TITLE
Snowflakes turns to ellipsis if width is low

### ISSUE THREAD

**Issue by Parallaps** [peterwetherall/snowfall#1] opened 2022-12-01 13:55 UTC
I used it in my project and with canvas size 270x1000px, all snowflakes turn to ellipsis.

It works fine if the canvas is square, but it's bad for thin containers

**Comment by pweth** [comment] 2022-12-05 17:56
Hi Arseniy,

Thanks for checking out this project!

I'm unable to reproduce the issue when I re-size a canvas to `270px` by `1000px` using the library (see screenshot below).

Please could you attach a code snippet here or link me to a page where it is bugging out the snowflakes?

Thanks,
Peter

![image](https://user-images.githubusercontent.com/22416843/205706375-a7d72284-cd92-4098-8e87-a78c61cd115a.png)

**Comment by Parallaps** [comment] 2022-12-07 12:22
Hi!

Added it to Codepen:
https://codepen.io/styre/pen/abKXjxQ

**Comment by pweth** [comment] 2022-12-10 12:48
Hi Arseniy,

Thank you for providing the Codepen link; I have a pushed a fix for the issue here: 18fd6a5bc6d761f4e570fa38b27625cad5b6ac24

Please let me know if you encounter any further bugs.

Thanks,
Peter

**Closed as completed by pweth** 2022-12-10 12:48 UTC

**Comment by Parallaps** [comment] 2022-12-11 13:13
Great, it works, thanks!
